# Generated by Django 4.2.3 on 2024-02-17 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('is_submitted', models.BooleanField(default=False)),
                ('name_of_degree', models.CharField(max_length=100)),
                ('admission_session', models.CharField(max_length=100)),
                ('reg_id_no', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('year_of_passing', models.CharField(max_length=100)),
                ('graduating_session', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
